### ISSUE TITLE
Error: timeout 

### ISSUE THREAD

**Issue by akhileshkumargangwar** [rohithreddy024/VAE-Text-Generation#1]
Hi, 
       I am getting following error. How to fix it. 
       Thanks
![screenshot from 2018-10-12 14-12-28](https://user-images.githubusercontent.com/28591199/46858606-487e0700-ce29-11e8-8944-130283aceb1d.png)

**Comment by rohithreddy024** [comment]
It seems that torchtext is unable to download pre-trained Glove vectors. If you don't want to use pre-trained wordvecs, do these modifications
In `dataset.py`,  replace line 48 
` text_field.build_vocab(train_data, val_data, max_size=opt.n_vocab-4, vectors='glove.6B.300d')`
with 
`text_field.build_vocab(train_data, val_data, max_size=opt.n_vocab-4)`
and
In `main.py`, comment out line 55
`vae.embedding.weight.data.copy_(vocab.vectors)`

**Comment by akhileshkumargangwar** [comment]
Thanks for quick reply. 
                         If I will not use  pre-trained word2vec model then what embedding it will use. I will run the code .
                       Thanks

**Comment by rohithreddy024** [comment]
Model will learn the embeddings from scratch.
